sudo: required
services:
    - docker
    
before_install:
    - docker build -t akhilbansalgmail/docker-react -f Dockerfile.dev .
    
script:
    - docker run akhilbansalgmail/docker-react npm run test -- --coverage